# Generated by Django 4.0.1 on 2022-01-14 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateField()),
                ('time_end', models.DateField(null=True)),
                ('subject', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=30)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('Class', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studenttopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='', max_length=200, verbose_name='答案')),
                ('mark', models.FloatField(default=0, verbose_name='分数')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.homework')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.student')),
            ],
        ),
    ]
