# Generated by Django 3.2.9 on 2021-12-13 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('wanted', models.IntegerField()),
                ('image', models.ImageField(upload_to='market/images')),
                ('uploadTime', models.DateTimeField()),
                ('Price', models.FloatField()),
                ('discription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.CharField(max_length=50)),
                ('userNickName', models.CharField(max_length=32)),
                ('userPhone', models.CharField(blank=True, max_length=32, null=True)),
                ('userAvatar', models.ImageField(blank=True, null=True, upload_to='market/avatars')),
                ('userAddress', models.CharField(blank=True, max_length=32, null=True)),
                ('userPassword', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageAddress', models.ImageField(upload_to='market/images')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.goods')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.users'),
        ),
    ]
