# Generated by Django 3.2.9 on 2022-01-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_users_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='nickname',
        ),
    ]
