# Generated by Django 3.2.9 on 2022-01-12 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_remove_users_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='market/images')),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('time', models.DateField()),
                ('wanted', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.users')),
            ],
        ),
    ]
