# Generated by Django 3.2.9 on 2022-01-12 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='time',
        ),
    ]
