# Generated by Django 3.2.9 on 2022-01-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_remove_item_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='wantlist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
